apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
data:
  databaseUrl: {{ .Values.env.databaseUrl | b64enc }}
  authServerUrl: {{ .Values.env.authServerUrl | b64enc }}
  authServerPathToken: {{ .Values.env.authServerPathToken | b64enc }}
  authServerPathAuthorize: {{ .Values.env.authServerPathAuthorize | b64enc }}
  cloudamqpUrl: {{ .Values.env.cloudamqpUrl | b64enc }}
  cloudamqpExchangeName: {{ .Values.env.cloudamqpExchangeName | b64enc }}
